server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-playlist
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spotify-dev
    username: usr-spotify 
    password: pwd-spotify 
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true


  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    
eureka:
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceURL:
         defaultZone: http://localhost:8761/eureka
         
resilience4j.circuitbreaker:
  instances:
    Music:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 20
      waitDurationInOpenState: 5000
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
   #  automaticTransitionFromOpenToHalfOpenEnabled: true

resilience4j.retry:
  instances:
    Music:
      maxAttempts: 2
      waitDuration: 30s
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
